test:
  secret_key_base: 'some-secret-key-SecureRandom.hex(64)'
development:
  secret_key_base: '9c0804dbb69fdf0a7643c4fdc24658acdd0ea92b36597eb4e575f55498106ac49e597dcc6eb3b3850f06fb7ae66119de9d5e7d9c8df88348899e26233fc3b964'
staging:
  secret_key_base: 'some-secret-key-SecureRandom.hex(64)'
production:
  secret_key_base: 'some-secret-key-SecureRandom.hex(64)'
